services:
  web:
    image: img_pymongo
    ports:
      - "5000:5000"
    deploy:
      replicas: 4
      update_config:
        parallelism: 2
        delay: 5s
        monitor: 20s
      placement:
        constraints:
          - node.labels.tipo == node_pymongo
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
